import turtle

t = turtle.Turtle()
t.shape('turtle')
lista = []
radius = int(input('원의 반지름은 ? '))
color = input('색상 #1을 입력하시오: ')
lista.append(color)
color = input('색상 #2을 입력하시오: ')
lista.append(color)
color = input('색상 #3을 입력하시오: ')
lista.append(color)
color = input('색상 #4을 입력하시오: ')
lista.append(color)
t.fillcolor(lista[0])
t.begin_fill()
t.circle(radius)
t.end_fill()
t.up()
t.goto((radius * 2), 0)
t.down()
t.fillcolor(lista[1])
t.begin_fill()
t.circle(radius)
t.end_fill()
t.up()
t.goto((radius * 2) * 2, 0)
t.down()
t.fillcolor(lista[2])
t.begin_fill()
t.circle(radius)
t.end_fill()
t.up()
t.goto((radius * 2) * 3, 0)
t.down()
t.fillcolor(lista[3])
t.begin_fill()
t.circle(radius)
t.end_fill()
